# Initial Setup

In [18]:
crmp_url = "postgresql+psycopg2://crmp@/crmp?host=pg01.pcic.uvic.ca,pg02.pcic.uvic.ca&port=5432,5432&target_session_attrs=read-write&passfile=/workspaces/climo-data-importer/.pgpass"
metnorth_url = "postgresql+psycopg2://metnorth_ro@/metnorth?host=pg01.pcic.uvic.ca,pg02.pcic.uvic.ca&port=5432,5432&target_session_attrs=read-write&passfile=/workspaces/climo-data-importer/.pgpass"

import logging
import pandas as pd
import sqlalchemy as sa
from sqlalchemy.orm import Session

crmp_engine = sa.create_engine(crmp_url, echo=False)
crmp_session = Session(crmp_engine)
metnorth_engine = sa.create_engine(metnorth_url, echo=False)
metnorth_session = Session(metnorth_engine)

## Pull networks from each session

In [20]:
q_network = sa.text("""
    SELECT * 
    FROM crmp.meta_network 
    WHERE network_name = :network_name
""")

with crmp_engine.begin() as connection:
    crmp_result = connection.execute(q_network, {"network_name": "EC_raw"})
    crmp_df = pd.DataFrame(crmp_result.fetchall(), columns=crmp_result.keys())

with metnorth_engine.begin() as connection:
    metnorth_result = connection.execute(q_network, {"network_name": "ECCC"})
    metnorth_df = pd.DataFrame(metnorth_result.fetchall(), columns=metnorth_result.keys())

display(crmp_df)
display(metnorth_df)

,network_id,network_name,description,virtual,publish,col_hex,contact_id,mod_time,mod_user,network_display_name
0,19,EC_raw,Environment and Climate Change Canada (raw obs...,None,True,#FF0000,None,2026-02-25 10:26:44.730224,tongli1997,EC_Raw

,network_id,network_name,description,virtual,publish,col_hex,contact_id,mod_time,mod_user,network_display_name
0,2,ECCC,Environment and Climate Change Canada,None,True,#ff0000,None,2025-09-17 12:02:06.131802,metnorth,ECCC

In [21]:
q_variables = sa.text("""
    SELECT *
    FROM crmp.meta_vars
    WHERE network_id = :network_id
""")

crmp_network_id = crmp_df["network_id"].iloc[0]
metnorth_network_id = metnorth_df["network_id"].iloc[0]

with crmp_engine.begin() as connection:
    crmp_result = connection.execute(q_variables, {"network_id": int(crmp_network_id)})
    crmp_df = pd.DataFrame(crmp_result.fetchall(), columns=crmp_result.keys())

with metnorth_engine.begin() as connection:
    metnorth_result = connection.execute(q_variables, {"network_id": int(metnorth_network_id)})
    metnorth_df = pd.DataFrame(metnorth_result.fetchall(), columns=metnorth_result.keys())

display(crmp_df)
display(metnorth_df)

,vars_id,network_id,unit,precision,standard_name,cell_method,long_description,net_var_name,display_name,short_name,mod_time,mod_user
0,542,19,Celsius,None,air_temperature,time: point,Hourly air temperature,air_temperature,Temperature (Point),air_temperature_point,2025-02-11 16:03:39.747374,crmp
1,543,19,km/h,None,wind_speed_of_gust,time: maximum,Maximum speed of wind gust,wind_gust_speed,Wind Gust (Max.),wind_speed_of_gust_maximum,2025-02-11 16:03:39.747374,crmp
2,545,19,Celsius,None,air_temperature,time: minimum,Minimum daily air temperature,air_temperature_yesterday_low,Temperature (Min.),air_temperature_minimum,2025-02-11 16:03:39.747374,crmp
3,544,19,Celsius,None,air_temperature,time: maximum,Maximum daily air temperature,air_temperature_yesterday_high,Temperature (Max.),air_temperature_maximum,2025-02-11 16:03:39.747374,crmp
4,551,19,Celsius,None,dew_point_temperature,time: point,Dew point,dew_point,Dew Point Temperature (Point),dew_point_temperature_point,2025-02-11 16:03:39.747374,crmp
5,550,19,km/h,None,wind_speed,time: point,Instantaneous wind speed,wind_speed,Wind Speed (Point),wind_speed_point,2025-02-11 16:03:39.747374,crmp
6,548,19,cm,None,thickness_of_snowfall_amount,time: sum,Daily snowfall,snow_amount,Snowfall Amount,thickness_of_snowfall_amount_sum,2025-02-11 16:03:39.747374,crmp
7,552,19,percent,None,relative_humidity,time: point,Relative humidity,relative_humidity,Relative Humidity (Point),relative_humidity_point,2025-02-11 16:03:39.747374,crmp
8,547,19,mm,None,thickness_of_rainfall_amount,time: sum,Daily rainfall amount,total_rain,Rainfall Amount,thickness_of_rainfall_amount_sum,2025-02-11 16:03:39.747374,crmp
9,613,19,celsius,None,air_temperature,t: maximum within days t: mean within months t...,Climatological mean of monthly mean maximum da...,Tx_Climatology,Temperature Climatology (Max.),air_temperaturet: maximum within days t: mean ...,2025-02-11 16:03:39.747374,crmp
10,555,19,kPa s-1,None,tendency_of_air_pressure,time: sum,Air pressure tendency,tendency_amount,Air Pressure Tendency,tendency_of_air_pressure_sum,2025-02-11 16:03:39.747374,crmp
11,553,19,degree,None,wind_from_direction,time: mean,Wind direction octants,wind_direction,Wind Direction (Mean),wind_from_direction_mean,2025-02-11 16:03:39.747374,crmp
12,554,19,percent,None,cloud_area_fraction,time: point,Total cloud cover,total_cloud_cover,Cloud Cover Fraction,cloud_area_fraction_point,2025-02-11 16:03:39.747374,crmp
13,546,19,mm,None,lwe_thickness_of_precipitation_amount,time: sum,Daily precipitation amount,total_precipitation,Precipitation Amount,lwe_thickness_of_precipitation_amount_sum,2025-02-11 16:03:39.747374,crmp
14,614,19,celsius,None,air_temperature,t: minimum within days t: mean within months t...,Climatological mean of monthly mean minimum da...,Tn_Climatology,Temperature Climatology (Min.),air_temperaturet: minimum within days t: mean ...,2025-02-11 16:03:39.747374,crmp
15,615,19,celsius,None,air_temperature,t: mean within days t: mean within months t: m...,Climatological mean of monthly mean of mean da...,T_mean_Climatology,Temperature Climatology (Mean),air_temperaturet: mean within days t: mean wit...,2025-02-11 16:03:39.747374,crmp
16,616,19,mm,None,lwe_thickness_of_precipitation_amount,t: sum within months t: mean over years,Climatological mean of monthly total precipita...,Precip_Climatology,Precipitation Climatology,lwe_thickness_of_precipitation_amountt: sum wi...,2025-02-11 16:03:39.747374,crmp
17,837,19,mm,None,thickness_of_rainfall_amount,time: sum,Daily rainfall,rain_amount,Rainfall,thickness_of_rainfall_amount_sum,2025-02-11 16:03:39.747374,crmp
18,549,19,kPa,None,mean_sea_level_pressure,time: point,Hourly mean seas level pressure,mean_sea_level,Mean Sea Level Pressure,mean_seal_level_pressure_point,2025-06-09 15:20:09.774817,hiebert

,vars_id,net_var_name,unit,standard_name,cell_method,precision,long_description,display_name,short_name,network_id,mod_time,mod_user
0,25,Snow_Water_equivalent_precipitation,mm,lwe_thickness_of_snowfall_amount,time: point,None,water equivalent snowfall,Snow Fall Water Equivalent,None,2,2025-09-17 12:02:06.131802,metnorth
1,27,Humidity,%,relative_humidity,time: point,None,relative humidity in percent,Relative Humidity,None,2,2025-09-17 12:02:06.131802,metnorth
2,32,Pressure,millibar,air_pressure,time: point,None,Atmospheric pressure,Atmospheric Pressure,None,2,2025-09-17 12:02:06.131802,metnorth
3,31,Visibility,km,visibility_in_air,time: point,None,Visibility,Visibility,None,2,2025-09-17 12:02:06.131802,metnorth
4,33,Weather,NULL,NULL,NULL,None,NaN,Present Weather,None,2,2025-09-17 12:02:06.131802,metnorth
5,28,Wind_Speed,km h-1,wind_speed,time: point,None,wind speed,Wind Speed,None,2,2025-09-17 12:02:06.131802,metnorth
6,51,Spd_of_Max_Gust,km h-1,wind_speed_of_gust,time: maximum,None,Daily maximum wind speed,Max Gust Speed,None,2,2025-09-17 12:02:06.131802,metnorth
7,29,Wind_direction,degrees,wind_from_direction,time: point,None,wind direction,Wind Direction,None,2,2025-09-17 12:02:06.131802,metnorth
8,34,Lake_Evaporation,mm,surface_water_evaporation_amount,time: sum,None,Lake evaporation,Lake Evaporation Amount,None,2,2025-09-17 12:02:06.131802,metnorth
9,35,Pan_Evaporation,mm,surface_water_evaporation_amount,time: sum,None,Pan evaporation,Pan Evaporation Amount,None,2,2025-09-17 12:02:06.131802,metnorth
10,36,Soil_Moisture,NaN,liquid_water_content_of_soil_layer,time: point,None,Soil Moisture,Soil Moisture,None,2,2025-09-17 12:02:06.131802,metnorth
11,37,Soil_Temperature,Celsius,soil_temperature,time: point,None,Soil temperature,Soil Temperature,None,2,2025-09-17 12:02:06.131802,metnorth
12,43,Max_Temp,Celsius,air_temperature,time: maximum,None,Maximum daily surface air temperature,Air Temperature (Max.),None,2,2025-09-17 12:02:06.131802,metnorth
13,44,Min_Temp,Celsius,air_temperature,time: minimum,None,Minimum daily surface air temperature,Air Temperature (Min.),None,2,2025-09-17 12:02:06.131802,metnorth
14,45,Mean_Temp,Celsius,air_temperature,time: mean,None,Mean daily surface air temperature,Air Temperature (Mean),None,2,2025-09-17 12:02:06.131802,metnorth
15,46,Total_Rain,mm,thickness_of_rainfall_amount,time: sum,None,Total liquid precipitation over 24 hour period,Daily Rainfall,None,2,2025-09-17 12:02:06.131802,metnorth
16,48,Total_Precipitation,mm,lwe_thickness_of_precipitation_amount,time: sum,None,Total precipitation water equivalent in a 24 h...,Daily Precipitation,None,2,2025-09-17 12:02:06.131802,metnorth
17,49,Snow_on_Grnd,cm,surface_snow_thickness,time: point,None,Present depth of snow,Snow Depth,None,2,2025-09-17 12:02:06.131802,metnorth
18,76,Dew_Point_Temp_degC,Celsius,dew_point_temperature,time: mean,None,Dew Point temperature,Dew Point Temperature,None,2,2025-09-17 12:02:06.131802,metnorth
19,47,daily_snow_24hr,cm,thickness_of_snowfall_amount,time: sum,None,Total snowfall thickness over 24 hour period,Daily Snowfall,None,2,2025-09-17 12:02:06.131802,metnorth
20,30,Solar_Radiation,W m-2,solar_irradiance,time: point,None,NaN,Solar Radiation,None,2,2025-09-17 12:02:06.131802,metnorth
21,50,Dir_of_Max_Gust,degrees,wind_gust_from_direction,time: point,None,Direction of daily maximum wind gust,Max Gust Direction,None,2,2025-09-17 12:02:06.131802,metnorth
22,26,Evaporation,mm,lwe_thickness_of_evaporation_amount,time: sum,None,evaporation amount,Evaporation Amount,None,2,2025-09-17 12:02:06.131802,metnorth
23,21,Temperature,Celsius,air_temperature,time: mean,None,Air temperature,Air Temperature,None,2,2025-09-17 12:02:06.131802,metnorth
24,22,Rainfall,mm,thickness_of_rainfall_amount,time: sum,None,Rainfall amount,Rainfall Amount,None,2,2025-09-17 12:02:06.131802,metnorth
25,23,Precipitation,mm,lwe_thickness_of_precipitation_amount,time: sum,None,Precipitation amount,Precipitation Amount,None,2,2025-09-17 12:02:06.131802,metnorth
26,24,snow_depth,cm,surface_snow_thickness,time: point,None,snow depth on the ground,Snow Depth,None,2,2025-09-17 12:02:06.131802,metnorth

In [24]:
crmp_vars = crmp_df[["net_var_name", "vars_id", "display_name"]].copy()
crmp_vars["_key"] = crmp_vars["net_var_name"].str.lower()

metnorth_vars = metnorth_df[["net_var_name", "vars_id", "display_name"]].copy()
metnorth_vars["_key"] = metnorth_vars["net_var_name"].str.lower()

merged = pd.merge(
    crmp_vars.rename(columns={"net_var_name": "crmp_net_var_name", "vars_id": "crmp_vars_id", "display_name": "crmp_display_name"}),
    metnorth_vars.rename(columns={"net_var_name": "metnorth_net_var_name", "vars_id": "metnorth_vars_id", "display_name": "metnorth_display_name"}),
    on="_key",
    how="outer",
).rename(columns={"_key": "net_var_name"})[["net_var_name", "crmp_net_var_name", "metnorth_net_var_name", "crmp_vars_id", "metnorth_vars_id", "crmp_display_name", "metnorth_display_name"]]

# 0 = both matched, 1 = crmp only, 2 = metnorth only
has_crmp = merged["crmp_vars_id"].notna()
has_metnorth = merged["metnorth_vars_id"].notna()
merged["_order"] = 2  # metnorth only default
merged.loc[has_crmp & ~has_metnorth, "_order"] = 1   # crmp only
merged.loc[has_crmp & has_metnorth, "_order"] = 0    # both matched

merged = merged.sort_values("_order").drop(columns="_order").reset_index(drop=True)

display(merged)

,net_var_name,crmp_net_var_name,metnorth_net_var_name,crmp_vars_id,metnorth_vars_id,crmp_display_name,metnorth_display_name
0,wind_speed,wind_speed,Wind_Speed,550.0,28.0,Wind Speed (Point),Wind Speed
1,wind_direction,wind_direction,Wind_direction,553.0,29.0,Wind Direction (Mean),Wind Direction
2,total_precipitation,total_precipitation,Total_Precipitation,546.0,48.0,Precipitation Amount,Daily Precipitation
3,total_rain,total_rain,Total_Rain,547.0,46.0,Rainfall Amount,Daily Rainfall
4,air_temperature,air_temperature,NaN,542.0,NaN,Temperature (Point),NaN
5,air_temperature_yesterday_high,air_temperature_yesterday_high,NaN,544.0,NaN,Temperature (Max.),NaN
6,air_temperature_yesterday_low,air_temperature_yesterday_low,NaN,545.0,NaN,Temperature (Min.),NaN
7,dew_point,dew_point,NaN,551.0,NaN,Dew Point Temperature (Point),NaN
8,tendency_amount,tendency_amount,NaN,555.0,NaN,Air Pressure Tendency,NaN
9,snow_amount,snow_amount,NaN,548.0,NaN,Snowfall Amount,NaN
10,t_mean_climatology,T_mean_Climatology,NaN,615.0,NaN,Temperature Climatology (Mean),NaN
11,tn_climatology,Tn_Climatology,NaN,614.0,NaN,Temperature Climatology (Min.),NaN
12,precip_climatology,Precip_Climatology,NaN,616.0,NaN,Precipitation Climatology,NaN
13,mean_sea_level,mean_sea_level,NaN,549.0,NaN,Mean Sea Level Pressure,NaN
14,relative_humidity,relative_humidity,NaN,552.0,NaN,Relative Humidity (Point),NaN
15,rain_amount,rain_amount,NaN,837.0,NaN,Rainfall,NaN
16,total_cloud_cover,total_cloud_cover,NaN,554.0,NaN,Cloud Cover Fraction,NaN
17,wind_gust_speed,wind_gust_speed,NaN,543.0,NaN,Wind Gust (Max.),NaN
18,tx_climatology,Tx_Climatology,NaN,613.0,NaN,Temperature Climatology (Max.),NaN
19,max_temp,NaN,Max_Temp,NaN,43.0,NaN,Air Temperature (Max.)
20,humidity,NaN,Humidity,NaN,27.0,NaN,Relative Humidity
21,pressure,NaN,Pressure,NaN,32.0,NaN,Atmospheric Pressure
22,rainfall,NaN,Rainfall,NaN,22.0,NaN,Rainfall Amount
23,precipitation,NaN,Precipitation,NaN,23.0,NaN,Precipitation Amount
24,pan_evaporation,NaN,Pan_Evaporation,NaN,35.0,NaN,Pan Evaporation Amount
25,min_temp,NaN,Min_Temp,NaN,44.0,NaN,Air Temperature (Min.)
26,mean_temp,NaN,Mean_Temp,NaN,45.0,NaN,Air Temperature (Mean)
27,lake_evaporation,NaN,Lake_Evaporation,NaN,34.0,NaN,Lake Evaporation Amount
28,evaporation,NaN,Evaporation,NaN,26.0,NaN,Evaporation Amount
29,dir_of_max_gust,NaN,Dir_of_Max_Gust,NaN,50.0,NaN,Max Gust Direction
30,daily_snow_24hr,NaN,daily_snow_24hr,NaN,47.0,NaN,Daily Snowfall
31,dew_point_temp_degc,NaN,Dew_Point_Temp_degC,NaN,76.0,NaN,Dew Point Temperature
32,temperature,NaN,Temperature,NaN,21.0,NaN,Air Temperature
33,spd_of_max_gust,NaN,Spd_of_Max_Gust,NaN,51.0,NaN,Max Gust Speed
34,soil_temperature,NaN,Soil_Temperature,NaN,37.0,NaN,Soil Temperature
35,solar_radiation,NaN,Solar_Radiation,NaN,30.0,NaN,Solar Radiation
36,soil_moisture,NaN,Soil_Moisture,NaN,36.0,NaN,Soil Moisture
37,snow_water_equivalent_precipitation,NaN,Snow_Water_equivalent_precipitation,NaN,25.0,NaN,Snow Fall Water Equivalent
38,snow_depth,NaN,snow_depth,NaN,24.0,NaN,Snow Depth
39,snow_on_grnd,NaN,Snow_on_Grnd,NaN,49.0,NaN,Snow Depth
40,weather,NaN,Weather,NaN,33.0,NaN,Present Weather
41,visibility,NaN,Visibility,NaN,31.0,NaN,Visibility